#!/bin/bash

echo
echo "System Report for $(hostname) generated by $(whoami), on $(date)"
echo

echo "System Information"
echo "------------------"
echo "OS: $(grep PRETTY_NAME /etc/os-release | cut -d= -f2 | tr -d '\"')"
echo "Uptime: $(uptime -p)"
echo "CPU: $(lscpu | grep 'Model name' | cut -d: -f2 | sed 's/^ *//')"
echo "RAM: $(free -h | awk '/Mem:/ {print $2}')"
echo "Disk(s): $(lsblk -d -o model,size | grep -v 'MODEL')"
echo "Video: $(lshw -C display | grep 'product' | head -1 | cut -d: -f2 | sed 's/^ *//')"
echo "Host Address: $(hostname -I | awk '{print $1}')"
echo "Gateway IP: $(ip route | grep default | awk '{print $3}')"
echo "DNS Server: $(grep nameserver /etc/resolv.conf | awk '{print $2}')"
echo
echo "System Status"
echo "-------------"
echo "Users Logged In: $(who | awk '{print $1}' | sort | uniq | paste -sd "," -)"
echo "Disk Space: $(df -h --output=target,avail | tail -n +2 | awk '{print $1 \" \" $2}' | paste -sd \", \" -)"
echo "Process Count: $(ps aux | wc -l)"
echo "Load Averages: $(uptime | awk -F'load average: ' '{print $2}')"
echo "Listening Network Ports: $(ss -tuln | grep LISTEN | awk '{print $5}' | cut -d: -f2 | sort -n | uniq | paste -sd \",\" -)"
echo "UFW Status: $(sudo ufw status | head -n 1)"
echo

